
def frame():
    print("\n\n\t\t" + "🔸" * 25)
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸\t    🏦  Bankkonto-Verwaltung 🏦   \t🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t" + "🔸" * 25)
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸   1️⃣   Konto anlegen\t\t\t  🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸   2️⃣   Konto auswählen\t\t\t  🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸   ❌  Beenden\t\t\t\t🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t" + "🔸" * 25)


def account_frame(selected_account):
    print("\n\t\t" + "🔸" * 25)
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸\t  Aktionen für Konto von " + selected_account.a_holder + "\t\t🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t" + "🔸" * 25)
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸   1️⃣  Einzahlen\t\t\t\t  🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸   2️⃣  Abheben\t\t\t\t  🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸   3️⃣  Kontostand anzeigen\t\t\t  🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸   4️⃣  Zinsen berechnen\t\t\t  🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t🔸   ❌ Zurück zum Hauptmenü\t\t\t🔸")
    print("\t\t🔸\t\t\t\t\t\t🔸")
    print("\t\t" + "🔸" * 25)